stages:
  - build
  - publish
  - analyze

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
  - CI_PUBLISH_VERSION=v$(date '+%Y%m%d')-$(echo $CI_COMMIT_SHA | cut -c1-10)

cache:
  untracked: true
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - "*/build"

build:gradle-build:
  stage: build
  script:
    - ./gradlew clean detekt test build
  artifacts:
    paths:
      - "build/libs/*.jar"
    expire_in: 1 day
  tags:
    - java11

publish:gradle-publish:
  stage: publish
  script:
    - ls -la build/libs/*.jar
    - echo "Version to publish - $CI_PUBLISH_VERSION"
    - |-
      ./gradlew publish \
        -Pversion=$CI_PUBLISH_VERSION \
        -PartifactoryMavenUrl=$CI_ARTIFACTORY_MAVEN_URL \
        -PartifactoryPublishUser=$CI_ARTIFACTORY_PUBLISH_USER \
        -PartifactoryPublishPassword=$CI_ARTIFACTORY_PUBLISH_PASSWORD
  only:
    refs:
      - master
      - tags
  tags:
    - java11

analyze:sonar-analyze:
  stage: analyze
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: ./gradlew detekt test jacocoTestReport build sonarqube
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never
  tags:
    - java11
